---

- name: Install nvm
  shell:  curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
  args:
    creates : "/{{ nvm.dir }}/.nvm/nvm.sh"
  tags:
    - nodejs

- name: Install node and set version
  shell: "nvm install {{ node.version }} && nvm alias default {{ node.version }}"
  args:
    creates: "/home/{{ account.user.name }}/.nvm/alias"
  tags:
    - nodejs

- name: install npm packages
  npm:
    name: "{{ item }}"
    global: True
    state: present
  become: True
  with_items: "{{ npm_packages }}"
  tags:
    - nodejs

